config/routes.rb
Rails.application.routes.draw do
  resources :comentarios
  resources :noticias
  root to: "paginas_estaticas#index"
  resources :usuarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comentario.rb
class Comentario < ApplicationRecord
  belongs_to :noticia
end

app/models/noticia.rb
class Noticia < ApplicationRecord
  mount_uploader :imagem, ImagemUploader

  has_many :comentarios
end

app/models/usuario.rb
class Usuario < ApplicationRecord

  has_secure_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :nome, presence: true, length: {maximum: 50}
  validates :password, length: {minimum: 6}
  validates :email, presence: true, length: {maximum: 255},
                                    format: {with: VALID_EMAIL_REGEX},
                                    uniqueness: { case_sensitive: true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_comentario, only: [:show, :edit, :update, :destroy]

  # GET /comentarios
  # GET /comentarios.json
  def index
    @comentarios = Comentario.all
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
  end

  # GET /comentarios/new
  def new
    @comentario = Comentario.new
  end

  # GET /comentarios/1/edit
  def edit
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    @comentario = Comentario.new(comentario_params)

    respond_to do |format|
      if @comentario.save
        format.html { redirect_to @comentario, notice: 'Comentario was successfully created.' }
        format.json { render :show, status: :created, location: @comentario }
      else
        format.html { render :new }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comentarios/1
  # PATCH/PUT /comentarios/1.json
  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to @comentario, notice: 'Comentario was successfully updated.' }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario.destroy
    respond_to do |format|
      format.html { redirect_to comentarios_url, notice: 'Comentario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comentario_params
      params.require(:comentario).permit(:autor, :conteudo, :noticia_id)
    end
end

app/controllers/noticias_controller.rb
class NoticiasController < ApplicationController
  before_action :set_noticia, only: [:show, :edit, :update, :destroy]

  # GET /noticias
  # GET /noticias.json
  def index
    @noticias = Noticia.all
  end

  # GET /noticias/1
  # GET /noticias/1.json
  def show
    @noticia = Noticia.find(params[:id])
    @comentario = @noticia.comentarios.build
  end

  # GET /noticias/new
  def new
    @noticia = Noticia.new
  end

  # GET /noticias/1/edit
  def edit
  end

  # POST /noticias
  # POST /noticias.json
  def create
    @noticia = Noticia.new(noticia_params)

    respond_to do |format|
      if @noticia.save
        format.html { redirect_to @noticia, notice: 'Noticia was successfully created.' }
        format.json { render :show, status: :created, location: @noticia }
      else
        format.html { render :new }
        format.json { render json: @noticia.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /noticias/1
  # PATCH/PUT /noticias/1.json
  def update
    respond_to do |format|
      if @noticia.update(noticia_params)
        format.html { redirect_to @noticia, notice: 'Noticia was successfully updated.' }
        format.json { render :show, status: :ok, location: @noticia }
      else
        format.html { render :edit }
        format.json { render json: @noticia.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /noticias/1
  # DELETE /noticias/1.json
  def destroy
    @noticia.destroy
    respond_to do |format|
      format.html { redirect_to noticias_url, notice: 'Noticia was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_noticia
      @noticia = Noticia.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def noticia_params
      params.require(:noticia).permit(:autor, :titulo, :conteudo, :imagem)
    end
end

app/controllers/paginas_estaticas_controller.rb
class PaginasEstaticasController < ApplicationController
    def index
        @nome = "Jovennan"
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nome, :email, :password_digest)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/noticias_helper.rb
module NoticiasHelper
end

app/helpers/paginas_estaticas_helper.rb
module PaginasEstaticasHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/comentarios/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 col-xs-12">
  <%= form_for(@comentario) do |f| %>
    <% if @comentario.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

        <ul>
        <% @comentario.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :autor %>
      <%= f.text_field :autor, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :conteudo %>
      <%= f.text_area :conteudo, class: 'form-control' %>
    </div>

    <div class="field">
      <%= f.hidden_field :noticia_id %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
  </div>
</div>

app/views/comentarios/edit.html.erb
<h1>Editing Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

app/views/comentarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comentarios</h1>

<table>
  <thead>
    <tr>
      <th>Autor</th>
      <th>Conteudo</th>
      <th>Noticia</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.autor %></td>
        <td><%= comentario.conteudo %></td>
        <td><%= comentario.noticia_id %></td>
        <td><%= link_to 'Show', comentario %></td>
        <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
        <td><%= link_to 'Destroy', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comentario', new_comentario_path %>

app/views/comentarios/new.html.erb
<h1>New Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Back', comentarios_path %>

app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Autor:</strong>
  <%= @comentario.autor %>
</p>

<p>
  <strong>Conteudo:</strong>
  <%= @comentario.conteudo %>
</p>

<p>
  <strong>Noticia:</strong>
  <%= @comentario.noticia_id %>
</p>

<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jornal</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-default navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <ul class="nav navbar-nav">
        <li><a href="/">Início</a></li>
        <li><a href="/noticias">Notícias</a></li>
      </ul>
    </div>
  </div>
</div>
    <div class="container">
  <%= yield %>
</div>
<footer>
  <div class="container">
    UNIPE 2017
  </div>
</footer>
  </body>
</html>

app/views/noticias/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 col-xs-12">
    <%= form_for(noticia, :html => { :multipart => true }) do |f| %>
      <% if noticia.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(noticia.errors.count, "error") %> prohibited this noticia from being saved:</h2>

          <ul>
          <% noticia.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :autor %>
        <%= f.text_field :autor, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :titulo %>
        <%= f.text_field :titulo, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :conteudo %>
        <%= f.text_area :conteudo, class: 'form-control', rows: '5' %>
      </div>

      <div class="form-group">
        <%= f.label :imagem %>
        <%= f.file_field :imagem, class: 'form-control' %>
      </div>

      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/noticias/edit.html.erb
<h1>Editing Noticia</h1>

<%= render 'form', noticia: @noticia %>

<%= link_to 'Mostrar', @noticia, class: 'btn btn-primary' %> |
<%= link_to 'Voltar', noticias_path, class: 'btn btn-default' %>

app/views/noticias/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Noticias</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Autor</th>
      <th>Titulo</th>
      <th>Conteudo</th>
      <th>Imagem</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @noticias.each do |noticia| %>
      <tr>
        <td><%= noticia.autor %></td>
        <td><%= noticia.titulo %></td>
        <td><%= noticia.conteudo %></td>
        <td><%= noticia.imagem %></td>
        <td><%= link_to 'Mostrar', noticia, class: 'btn btn-primary' %></td>
        <td><%= link_to 'Editar', edit_noticia_path(noticia), class: 'btn btn-warning' %></td>
        <td><%= link_to 'Excluir', noticia, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Notícia', new_noticia_path, class: 'btn btn-primary' %>

app/views/noticias/new.html.erb
<h1>New Noticia</h1>

<%= render 'form', noticia: @noticia %>

<%= link_to 'Back', noticias_path %>

app/views/noticias/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Autor:</strong>
  <%= @noticia.autor %>
</p>

<p>
  <strong>Titulo:</strong>
  <%= @noticia.titulo %>
</p>

<p>
  <strong>Conteudo:</strong>
  <%= @noticia.conteudo %>
</p>

<p>
  <strong>Imagem:</strong>
  <%= image_tag(@noticia.imagem_url, :width => 600) if @noticia.imagem.present? %>
</p>

<h3>Novo Comentário</h3>
<%= render 'comentarios/form' %>

<h3>Comentários</h3>
<% @noticia.comentarios.each do |comentario| %>
  <div>
    <strong><%= comentario.autor %></strong>
    <br />
    <p><%= comentario.conteudo %><p>
  </div>
<% end %>

<%= link_to 'Edit', edit_noticia_path(@noticia) %> |
<%= link_to 'Back', noticias_path %>

app/views/paginas_estaticas/index.html.erb
<h1>Olá Rails<h1>

<%= @nome %>

app/views/usuarios/_form.html.erb
<div class="col-md-6 col-md-offset-3 col-xs-12">
<%= form_for(usuario) do |f| %>
  <% if usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome %>
    <%= f.text_field :nome, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.text_field :password, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.text_field :password_confirmation, class:'form-control' %>
  </div>

  <div class="action">
    <%= f.submit 'Enviar', class: 'btn btn-primary' %>
  </div>
<% end %>
</div>

app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nome %></td>
        <td><%= usuario.email %></td>
        <td><%= usuario.password_digest %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>New Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @usuario.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @usuario.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @usuario.password_digest %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>